language: ruby

services:
  - docker

install:
# Download ghr
- curl -L https://github.com/tcnksm/ghr/releases/download/v0.12.0/ghr_v0.12.0_linux_amd64.tar.gz | tar zxf -
# Install ghr
- sudo mv ghr_v0.12.0_linux_amd64/ghr /usr/local/bin

script:
- ruby build.rb
